### ISSUE TITLE
tmpfs is not cleared after adding files with storeDirectory

### ISSUE THREAD

**Issue by ljmf00** [nftstorage/nft.storage#1186]
By using the `client.storeDirectory`, after adding files to the IPFS network, the tmpfs /tmp is not cleaned up properly, cluttering it over time.

```js
import { NFTStorage, File } from 'nft.storage'
import { pack } from 'ipfs-car/pack'
import process from 'process'
import minimist from 'minimist'
import fs from 'fs'

const args = minimist(process.argv.slice(2))

const NS_API_KEY = fs.readFileSync('ns-api-key.txt','utf8').trim();
const nsclient = new NFTStorage({ token: NS_API_KEY })
const nsfiles = []

function getFiles (dir, files_){
    files_ = files_ || [];
    var files = fs.readdirSync(dir);
    for (var i in files){
        var name = dir + '/' + files[i];
        if (fs.statSync(name).isDirectory()){
            getFiles(name, files_);
        } else {
            files_.push(name);
        }
    }
    return files_;
}

for (const path of args._)
  nsfiles.push(...getFiles(path)
    .map(f => new File([fs.readFileSync(f)], f)))

const nscid = await nsclient.storeDirectory(nsfiles)
console.log(nscid)
```

**Comment by vasco-santos** [comment]
@ljmf00 thanks for the replication case. We had a bug on `storeBlob` and `storeDirectory` which is addressed in https://github.com/nftstorage/nft.storage/pull/1198

**Comment by ljmf00** [comment]
Thanks for fixing it!

**Comment by HomeSchoolDev** [comment]
This still appears to be happening on the latest 7.0.0 store()
