### ISSUE TITLE
My nft images cannot be accessed

### ISSUE THREAD

**Issue by fx168caijing** [nftstorage/nft.storage#2795]
hello，I need your help,All my nft websites cannot access nft images,such as:
https://www.fx168news.com/nft/shop/sheerroom
https://www.fx168news.com/nft/shop/light
https://www.fx168news.com/nft/shop/herpower

all nft picture show:
https://nftstorage.link/ipfs/bafybeihrcfpgvwpyzpa7ldhexdhhspkf4v3bma7cfbicbrbwl4lt2z3dce/16732485730001%25E7%2589%259B%25E5%258D%258E.gif
This website has been reported for potential phishing.
Phishing is when a site attempts to steal sensitive information by falsely presenting as a safe source.

and I also can not login my account :tan.aidong@fx168group.com,the login page show 404：
https://classic.nft.storage/login

how to login in,and get my nft data,pls help me

**Comment by elizabeth-griffiths** [comment]
Hi there,

Thank you for reaching out. Let’s tackle your concerns one at a time:
1. *Access and Login Issues*

You mentioned being unable to log into your account at
https://classic.nft.storage/login. This is because *NFT.Storage Classic*
has transitioned, and new logins are no longer available. You should access
the current NFT.Storage login at the following link: 👉 *Login URL:*
https://app.nft.storage/login
2. *NFT Image Access Issues and Phishing Warning*

Regarding the NFT image URL (
https://nftstorage.link/ipfs/bafybeihrcfpgvwpyzpa7ldhexdhhspkf4v3bma7cfbicbrbwl4lt2z3dce/16732485730001%25E7%2589%259B%25E5%258D%258E.gif),
the phishing warning you encountered might be due to a security filter or
block placed by the website you are using.

*How to address this:*

   - *Raise an appeal:* Report the false positive to the relevant service
   flagging the content. The more users who submit reports, the quicker it
   gets cleared.
   - *Direct action from our side:* We will also raise this issue from our
   end to accelerate the resolution.

*Alternative Solutions:*

   - *Copy Your Data to Pinata or Lighthouse:*
   You can migrate your pinned data from *NFT.Storage Classic* to *Pinata*
   or *Lighthouse* for faster and more secure access. This ensures better
   stability and service for your NFT content. Here’s a guide on how to
   seamlessly copy your data:
   👉
   https://nft.storage/blog/why-copy-your-nft-storage-classic-data-and-how-to-do-it

------------------------------
3. *Next Steps*

   - Please try logging in at the updated URL and let us know if the issue
   persists.
   - If the phishing warning continues, we’ll follow up directly with the
   website operators.
   - Consider moving your NFT content to a different gateway like *Pinata
   or Lighthouse* to avoid future interruptions.

We’re here to help you preserve your NFT data for the long term. Feel free
to reach out again if you have more questions.

Best regards,
*NFT.Storage Support Team*

**Comment by elizabeth-griffiths** [comment]
The issue with your NFT images has been resolved. It turns out Phantom was blocking our content, but we’ve sorted it out with them, and access should be restored now.

Let us know if you run into any other issues!

**Comment by fx168caijing** [comment]
![Image](https://github.com/user-attachments/assets/8925018d-7124-4916-bb80-c6766c1907c3)I still can't access old NFT images，it show “Sorry, you have been blocked
You are unable to access nftstorage.link”，
and I know my nft api key ,but I don't know how to login in new site,I try much times,I'll tell you my NFT APK key, can you help me retrieve my account and password

**Comment by elizabeth-griffiths** [comment]
"Sorry, you have been blocked" is not related to your user/password. Please
email ***@***.*** so we can work with you to resolve this.

**Comment by fx168caijing** [comment]
Sorry, I am unable to view the complete email address

**Comment by fx168caijing** [comment]
![Image](https://github.com/user-attachments/assets/017a1ac7-83d8-4610-a711-825ac1b264f9)
Sorry, I am unable to view the complete email address. Could you please send a picture with the email address included

**Comment by elizabeth-griffiths** [comment]
support
at
nft.storage
